import React, { useEffect, useRef } from 'react'
import { staggerEnter, MOTION } from '../../utils/motion'

export function AIExplanation({
  t = {},
  language = 'en',
  optResult,
  aiState = 'IDLE',
  aiData = null,
  aiError = '',
  onRunAIExplanation
}) {
  const isRu = language === 'ru'
  const currentAI = aiData || optResult?.ai
  const contentRef = useRef(null)

  useEffect(() => {
    if (currentAI && contentRef.current) {
      const blocks = contentRef.current.children
      staggerEnter(blocks, { baseDelay: MOTION.staggerMedium, duration: MOTION.normal, y: 8 })
    }
  }, [currentAI])

  const isAi = Boolean(currentAI?.is_ai ?? (currentAI?.provider === 'gemini'))
  const provenanceLabel = isAi
    ? (isRu ? 'ИИ-АНАЛИЗ' : 'AI ANALYSIS')
    : (isRu ? 'ПРАВИЛО-ОРИЕНТИРОВАННОЕ РЕЗЮМЕ' : 'RULE-BASED SUMMARY')

  const positioningHeadline = isRu
    ? (optResult?.insights?.headline_ru || optResult?.insights?.headline || t.neighborhoodPlatform || 'URBANMIND — платформа цифрового двойника города для локальных решений по светофорам и потокам.')
    : (optResult?.insights?.headline_en || optResult?.insights?.headline || t.neighborhoodPlatform || 'URBANMIND is a digital twin platform for local signal and flow decisions.')

  const positioningContext = isRu
    ? (optResult?.insights?.context_ru || optResult?.insights?.context || t.neighborhoodContext || 'Она помогает городским службам действовать до того, как заторы начнут влиять на повседневное движение и доступность.')
    : (optResult?.insights?.context_en || optResult?.insights?.context || t.neighborhoodContext || 'It helps urban teams act before congestion affects daily movement and access.')

  return (
    <>
      <div className="panel-card ai-explanation-panel">
        <div className="card-header-with-badge">
          <h3>{t.whyChoice || (isRu ? 'Почему именно это решение?' : 'Why this choice?')}</h3>
          {currentAI && (
            <span className={`provenance-badge ${isAi ? 'ai' : 'fallback'}`} title={isAi ? 'Generated by Gemini LLM using simulation metrics' : 'Deterministic rule-based summary (offline mode)'}>
              {provenanceLabel}
            </span>
          )}
        </div>

        {!optResult ? (
          <p className="traffic-legend muted">
            {t.explanationAfter || (isRu ? 'Запустите оптимизацию, чтобы сформировать ИИ-аналитику решения.' : 'Run optimization to generate AI-assisted decision explanation.')}
          </p>
        ) : aiState === 'ANALYZING' ? (
          <div className="ai-loading-state" style={{ padding: '1.5rem 1rem', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '0.75rem', textAlign: 'center' }}>
            <svg className="spin-icon" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <path d="M21 12a9 9 0 1 1-6.219-8.56"></path>
            </svg>
            <span style={{ fontSize: '0.9rem', color: 'var(--accent-primary)', fontWeight: 500 }}>
              {t.analyzingResults || (isRu ? 'Анализ результатов симуляции с помощью Gemini AI…' : 'Analyzing simulation results with Gemini AI…')}
            </span>
          </div>
        ) : aiState === 'ERROR' ? (
          <div className="ai-error-state" style={{ padding: '1rem', background: 'rgba(239, 68, 68, 0.08)', borderRadius: '8px', border: '1px solid rgba(239, 68, 68, 0.2)' }}>
            <p className="error-text" style={{ color: '#f87171', fontSize: '0.88rem', margin: 0 }}>
              {aiError || (isRu ? 'Не удалось связаться с сервисом ИИ-аналитики.' : 'Unable to connect to AI reasoning service.')}
            </p>
            {onRunAIExplanation && (
              <button type="button" className="ghost-button mt-2" onClick={() => onRunAIExplanation(language)} style={{ marginTop: '0.75rem', fontSize: '0.82rem' }}>
                {t.retryAI || (isRu ? 'Повторить попытку' : 'Retry AI Analysis')}
              </button>
            )}
          </div>
        ) : currentAI ? (
          <div className="ai-content-body" ref={contentRef}>
            {/* 1. Summary Block */}
            {currentAI.summary && (
              <div className="ai-assessment-block" style={{ marginBottom: '1rem' }}>
                <span className="ai-block-title">
                  <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                    <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon>
                  </svg>
                  {t.aiSummary || (isRu ? 'Ключевые выводы' : 'AI Interpretation & Summary')}
                </span>
                <p className="ai-reasoning-text" style={{ fontSize: '0.88rem', color: 'var(--text-primary)', lineHeight: 1.45, marginTop: '0.35rem' }}>
                  {currentAI.summary}
                </p>
              </div>
            )}

            {/* 2. Key Improvements */}
            {Array.isArray(currentAI.key_improvements) && currentAI.key_improvements.length > 0 && (
              <div className="ai-findings-block" style={{ marginBottom: '0.9rem' }}>
                <span className="tradeoffs-title" style={{ color: '#4ade80', fontSize: '0.78rem' }}>
                  🟢 {t.keyImprovements || (isRu ? 'Что улучшилось' : 'Key Improvements')}
                </span>
                <ul className="tradeoffs-list" style={{ marginTop: '0.35rem', display: 'grid', gap: '0.3rem', paddingLeft: '1.1rem' }}>
                  {currentAI.key_improvements.map((item, idx) => (
                    <li key={idx} style={{ fontSize: '0.82rem', color: 'var(--text-primary)' }}>{item}</li>
                  ))}
                </ul>
              </div>
            )}

            {/* 3. Trade-offs */}
            {Array.isArray(currentAI.tradeoffs) && currentAI.tradeoffs.length > 0 && (
              <div className="ai-caveats-block" style={{ marginBottom: '0.9rem' }}>
                <span className="tradeoffs-title" style={{ color: '#fbbf24', fontSize: '0.78rem' }}>
                  🟡 {t.tradeoffs || (isRu ? 'Операционные компромиссы' : 'Operational Trade-offs')}
                </span>
                <ul className="tradeoffs-list" style={{ marginTop: '0.35rem', display: 'grid', gap: '0.3rem', paddingLeft: '1.1rem' }}>
                  {currentAI.tradeoffs.map((item, idx) => (
                    <li key={idx} style={{ fontSize: '0.82rem', color: 'var(--text-primary)' }}>{item}</li>
                  ))}
                </ul>
              </div>
            )}

            {/* 4. What to watch / Concerns */}
            {Array.isArray(currentAI.concerns) && currentAI.concerns.length > 0 && (
              <div className="ai-caveats-block" style={{ marginBottom: '0.9rem' }}>
                <span className="tradeoffs-title" style={{ color: '#93c5fd', fontSize: '0.78rem' }}>
                  ℹ️ {t.whatToWatch || (isRu ? 'На что обратить внимание' : 'What to Watch & Monitor')}
                </span>
                <ul className="tradeoffs-list" style={{ marginTop: '0.35rem', display: 'grid', gap: '0.3rem', paddingLeft: '1.1rem' }}>
                  {currentAI.concerns.map((item, idx) => (
                    <li key={idx} style={{ fontSize: '0.82rem', color: 'var(--text-primary)' }}>{item}</li>
                  ))}
                </ul>
              </div>
            )}

            {/* 5. Recommendation */}
            {currentAI.recommendation && (
              <div style={{ background: 'rgba(56, 189, 248, 0.08)', padding: '0.7rem 0.9rem', borderRadius: '8px', border: '1px solid rgba(56, 189, 248, 0.25)', marginTop: '0.75rem' }}>
                <strong style={{ fontSize: '0.78rem', color: 'var(--accent-primary)', textTransform: 'uppercase', letterSpacing: '0.04em', display: 'block', marginBottom: '0.25rem' }}>
                  {t.recommendation || (isRu ? 'Рекомендация для планировщиков' : 'Actionable Recommendation')}
                </strong>
                <p style={{ margin: 0, fontSize: '0.85rem', color: 'var(--text-primary)', lineHeight: 1.4 }}>
                  {currentAI.recommendation}
                </p>
              </div>
            )}

            <div className="ai-meta-row" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '0.9rem', fontSize: '0.78rem', color: 'var(--text-muted)' }}>
              <span>
                {t.confidence || (isRu ? 'Уверенность модели' : 'Confidence')}: <strong style={{ color: 'var(--text-primary)' }}>{currentAI.confidence || 'medium'}</strong>
              </span>
              <span>{currentAI.signal_focus}</span>
            </div>

            {onRunAIExplanation && (
              <button type="button" className="ghost-button mt-3" onClick={() => onRunAIExplanation(language)} style={{ marginTop: '0.9rem', width: '100%', justifyContent: 'center', fontSize: '0.82rem' }}>
                {t.refreshAI || (isRu ? 'Пересчитать ИИ-анализ' : 'Re-evaluate with AI')}
              </button>
            )}
          </div>
        ) : (
          <div className="ai-ready-state" style={{ padding: '0.5rem 0' }}>
            <p className="traffic-legend muted" style={{ marginBottom: '0.75rem' }}>
              {t.readyForAI || (isRu ? 'Оптимизация завершена. Запустите глубокий ИИ-анализ транспортных компромиссов.' : 'Optimization complete. Request deep AI operational reasoning on trade-offs.')}
            </p>
            {onRunAIExplanation && (
              <button type="button" className="accent" onClick={() => onRunAIExplanation(language)} style={{ width: '100%', justifyContent: 'center' }}>
                {t.runAIAnalysis || (isRu ? 'Запустить ИИ-анализ' : 'Run AI Analysis')}
              </button>
            )}
          </div>
        )}
      </div>

      <div className="panel-card">
        <h3>{t.mahallaPosition || (isRu ? 'Позиционирование URBANMIND' : 'URBANMIND Position')}</h3>
        <p className="recommendation-tag">{t.neighborhoodMobilityIntelligence || (isRu ? 'Цифровой двойник городской мобильности' : 'Urban digital twin platform')}</p>
        <p style={{ marginTop: '0.35rem', color: 'var(--text-primary)', lineHeight: 1.45 }}>{positioningHeadline}</p>
        <p className="selection-reason" style={{ marginTop: '0.5rem', color: 'var(--text-secondary)', lineHeight: 1.4 }}>{positioningContext}</p>
      </div>
    </>
  )
}
